version: '3.3'
volumes:
  data:
services:
  db:
    image: mysql:5.6
    ports:
      - "3308:3308"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=laravel
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8084:80
    environment:
      - PMA_ARBITRARY=1
