CREATE TABLE aluno (
matricula INT(11) PRIMARY KEY NOT NULL, 
nome VARCHAR(255) NOT NULL, 
curso VARCHAR(30) NOT NULL,
senha INT(10) NOT NULL);

CREATE TABLE admin (
id_admin INT(11) PRIMARY KEY NOT NULL, 
nome VARCHAR(255) NOT NULL,
senha INT(10) NOT NULL);

CREATE TABLE resposta (
id_resposta INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL, 
status INT(1), 
descricao TEXT, 
id_reclamacao INT(11) NOT NULL REFERENCES reclamacao(id_reclamacao) ON DELETE CASCADE ON UPDATE CASCADE, 
id_admin INT(11) NOT NULL REFERENCES admin(id_admin) ON DELETE CASCADE ON UPDATE CASCADE, 
data_resposta DATETIME);

CREATE TABLE restaurante (
id_restaurante INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL, 
campus VARCHAR(30) NOT NULL, 
setor VARCHAR(30) NOT NULL, 
local VARCHAR(30) NOT NULL);

CREATE TABLE reclamacao (
id_reclamacao INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL, 
data_ocorrencia DATETIME NOT NULL, 
categoria VARCHAR(50), 
descricao TEXT NOT NULL, 
id_restaurante INT(11) UNIQUE KEY NOT NULL REFERENCES restaurante(id_restaurante) ON DELETE CASCADE ON UPDATE CASCADE, 
id_resposta INT(11) UNIQUE KEY NOT NULL REFERENCES resposta(id_resposta) ON DELETE CASCADE ON UPDATE CASCADE, 
id_prato INT(11) UNIQUE KEY NOT NULL REFERENCES prato(id_prato) ON DELETE CASCADE ON UPDATE CASCADE, 
id_aluno INT(11) UNIQUE KEY NOT NULL REFERENCES aluno(matricula) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE prato (
id_prato INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
nome VARCHAR(255) NOT NULL, 
descricao TEXT, 
classificacao INT(1), 
id_reclamacao INT(11) NOT NULL REFERENCES reclamacao(id_reclamacao) ON DELETE SET NULL ON UPDATE CASCADE); 

CREATE TABLE ingrediente (
id_ingrediente INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL, 
nome VARCHAR(255) NOT NULL, 
descricao TEXT);

CREATE TABLE restaurante_serve (
turno VARCHAR(30), 
dia_semana VARCHAR(30), 
id_prato INT(11) UNIQUE KEY NOT NULL REFERENCES prato(id_prato) ON DELETE CASCADE ON UPDATE CASCADE, 
id_restaurante INT(11) UNIQUE KEY NOT NULL REFERENCES restaurante(id_restaurante) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE resposta_admin (
data DATE, 
id_resposta INT(11) UNIQUE KEY NOT NULL REFERENCES resposta(id_resposta) ON DELETE CASCADE ON UPDATE CASCADE, 
id_admin INT(11) UNIQUE KEY NOT NULL REFERENCES admin(id_admin) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE admin_gerencia (
id_admin INT(11) PRIMARY KEY NOT NULL REFERENCES admin(id_admin) ON DELETE CASCADE ON UPDATE CASCADE, 
id_restaurante INT(11) UNIQUE KEY NOT NULL REFERENCES restaurante(id_restaurante) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE ingredientes_prato (
id_prato INT(11) PRIMARY KEY NOT NULL REFERENCES prato(id_prato) ON DELETE CASCADE ON UPDATE CASCADE, 
id_restaurante INT(11) UNIQUE KEY NOT NULL REFERENCES restaurante(id_restaurante) ON DELETE CASCADE ON UPDATE CASCADE);
