version: '3'

services: 
    laravel-app:
        build: .
        ports: 
            - "8080:80" #porta do container

        volumes:
            - ./:/usr/share/nginx
            - .docker/nginx:/etc/nginx/conf.d/

        networks: 
            - app-network

    mysql-app:
        image: mysql:5.7.22
        ports: 
            - "3306:3306"
        #volumes: 
            #- .docker/dbdata:/var/lib/mysql #cada instancia, ele salva para não perder os dados
        environment: 
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: 123456
        networks: 
            - app-network
networks: 
    app-network:
        driver: bridge
